version:  "3"
services:
    nginx:
      image: insight/nginx
      build: 
        context: nginx
      ports:
        - 8080:80

    # the name of the service is resolvable by name
    # within the same docker network
    frontend-app:
      image: insight/frontend-app
      build: 
        context: frontend-app

    iframe-app:
      image: bonomat/nodejs-hello-world 